name: lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          output=$(dartfmt --dry-run lib/**/*.dart)
          if [ -z $output]
            then exit 0
          else
            exit 1
          fi
